[build]
  command = "npm run build"
  publish = "out"

[functions]
  included_files = ["public/assets/watermark.png"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200